# Generated by Django 5.1.5 on 2025-02-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbPopulate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsitedata',
            options={'verbose_name_plural': 'GSite Data'},
        ),
    ]
