# Generated by Django 5.1.5 on 2025-02-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbPopulate', '0002_alter_gsitedata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRecords',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Town', models.CharField(max_length=200)),
                ('Region', models.CharField(max_length=200)),
                ('Number_of_Galamsay_Sites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=150)),
                ('DateUploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GSiteData',
        ),
        migrations.AddField(
            model_name='siterecords',
            name='FileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FileID', to='DbPopulate.uploadedfile'),
        ),
    ]
