# Generated by Django 5.1.5 on 2025-02-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbPopulate', '0003_siterecords_uploadedfile_delete_gsitedata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterecords',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='ID',
            new_name='id',
        ),
    ]
